export const PROJECT_EDITOR_STRINGS = {
  titleKicker: 'Trama - Phase 2 kickoff',
  title: 'Project Scan + Markdown Editing Loop',
  preloadAvailable: 'disponible',
  preloadUnavailable: 'no disponible',
  openFolder: 'Elegir carpeta',
  opening: 'Abriendo...',
  noFolderSelected: 'Ninguna carpeta seleccionada',
  markdownFilesTitle: 'Archivos markdown',
  noMarkdownFiles: 'No hay archivos .md detectados.',
  editorTitle: 'Editor',
  noChanges: 'Sin cambios',
  saveNow: 'Guardar ahora',
  saving: 'Guardando...',
  noFileSelected: 'Selecciona un archivo para editar.',
  conflictTitlePrefix: 'El archivo activo cambio fuera de Trama:',
  conflictReload: 'Recargar y perder cambios',
  conflictKeep: 'Mantener mi edicion',
  initialStatus: 'Abre una carpeta de proyecto para iniciar.',
  projectOpeningStatus: 'Abriendo proyecto...',
  projectWithoutMarkdown: 'Proyecto abierto sin archivos .md aun.',
  folderSelectionCanceled: 'Seleccion de carpeta cancelada.',
  statusSaveAsCopyHint: 'Se mantuvieron los cambios locales. Puedes guardar como copia mas adelante.',
  statusReloadDiscarded: 'Contenido recargado desde disco. Se descartaron cambios locales.',
  statusNeedSaveBeforeSwitch: 'Guarda o espera autosave antes de cambiar de documento.',
  statusNeedSaveBeforeRefresh: 'Se detectaron cambios externos. Guarda primero para refrescar el arbol sin perder edicion.',
} as const
