export const PROJECT_EDITOR_STRINGS = {
  titleKicker: 'Trama - Phase 2 kickoff',
  title: 'Project Scan + Markdown Editing Loop',
  preloadAvailable: 'available',
  preloadUnavailable: 'unavailable',
  openFolder: 'Select Folder',
  opening: 'Opening...',
  noFolderSelected: 'No folder selected',
  markdownFilesTitle: 'Markdown files',
  noMarkdownFiles: 'No .md files detected.',
  editorTitle: 'Editor',
  noChanges: 'No changes',
  saveNow: 'Save now',
  saving: 'Saving...',
  noFileSelected: 'Select a file to start editing.',
  conflictTitlePrefix: 'The active file changed outside Trama:',
  conflictReload: 'Reload and discard local changes',
  conflictKeep: 'Keep my local edits',
  conflictSaveAsCopy: 'Save as copy',
  conflictCompare: 'Compare',
  conflictCompareClose: 'Close compare',
  conflictDiskVersion: 'Disk version',
  conflictLocalVersion: 'Your local version',
  initialStatus: 'Open a project folder to begin.',
  projectOpeningStatus: 'Opening project...',
  projectWithoutMarkdown: 'Project opened with no .md files yet.',
  folderSelectionCanceled: 'Project folder selection was canceled.',
  statusSaveAsCopyHint: 'Local edits were kept. You can save as copy later.',
  statusSaveAsCopyCreated: 'Conflict copy saved and opened to continue editing.',
  statusSaveAsCopyFailed: 'Failed to save conflict copy.',
  statusCompareReady: 'Compare view is ready: review disk vs local changes.',
  statusCompareFailed: 'Failed to prepare conflict comparison.',
  statusReloadDiscarded: 'Content reloaded from disk. Local changes were discarded.',
  statusNeedSaveBeforeSwitch: 'Save or wait for autosave before switching files.',
  statusNeedSaveBeforeRefresh: 'External changes detected. Save first to refresh the tree safely.',
} as const
